apiVersion: v1
kind: ReplicationController
metadata:
  name: maha-rc
spec:
  replicas: 5
  selector:
    app: mynginx
  template:
    metadata: 
      labels:
        app: mynginx
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80